- user: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    region: Us-east-1
    sg_id: sg-0b10412d77bb679e9
    zone_id: Z03935562DFKW1R55AYOI
    domain_name: yarabala.space
    instance:
    - mongodb

    - name: validate input variables
      ansible.builtin.debug:
        msg:
        - "AMI ID: {{ ami_id }}"
        - "Region: {{ region }}"
        - "Security Group ID: {{ sg_id }}"
        - "Instance List: {{ instance }}"

    tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        region: "{{ region }}"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instance }}"
      register: ec2_output

    - name: print the ec2_output
      ansible.builtin.debug:
        msg: "{{ec2_output}}"
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3
  #   region: us-east-1
  #   ec2_instance_type: t2.micro
  #   ec2_image: ami-0c02fb55956c7d316
  #   key_pair: devops86s
  #   security_group: sg-0b10412d77bb679e9
  #   instance_count: 1
  #   subnet_id: subnet-0f39e5fb394338efd
  #   zone: us-east-1a
  #   #zone_id: "Z03935562DFKW1R55AYOI"
  #   domain_name: yarabala.space
  #   record_name: www.yarabala.space
  #   ttl: 300
  # tasks:
  #  - name: launch ec2 instance
  #    amazon.aws.ec2_instance:
  #     name: "devops86s-web"
  #     key_name: "{{ key_pair }}"
  #     instance_type: "{{ ec2_instance_type }}"
  #     image_id: "{{ ec2_image }}"
  #     region: "{{ region }}"
  #     wait: yes
  #     count: "{{ instance_count }}"
  #     vpc_subnet_id: "{{ subnet_id }}"
  #     assign_public_ip: yes
  #     security_group_ids:
  #       - "{{ security_group }}"
  #    register: ec2

  #  - name: print the ec2 information
  #    ansible.builtin.debug:
  #     var: ec2

  #  - name: add new r53 record for the new ec2 instance
  #    community.aws.route53:
  #     state: present
  #     zone: "{{ domain_name }}"
  #     record: "{{ record_name }}"
  #     type: A
  #     ttl: "{{ ttl }}"
  #     value: "{{ ec2.instances[0].public_ip }}"